# Generated by Django 5.2.17 on 2026-10-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_distributor_custuser_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='oa_scope',
            field=models.CharField(default='snsapi_base', help_text='snsapi_base（静默）/ snsapi_userinfo（弹窗授权）', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='wechat_appsecret',
            field=models.CharField(blank=True, default='', help_text='公众号 AppSecret（网页授权 code 换 openid 用）', max_length=64),
        ),
    ]
