# Generated by Django 5.2.17 on 2026-09-30 12:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default=core.models.gen_order_no, editable=False, max_length=36, unique=True)),
                ('package_id', models.IntegerField(help_text='对应平台 QueryConfig.id')),
                ('package_name', models.CharField(blank=True, max_length=128)),
                ('subject_name', models.CharField(help_text='被查询人姓名', max_length=64)),
                ('subject_id_card', models.CharField(help_text='身份证号', max_length=32)),
                ('subject_phone', models.CharField(blank=True, max_length=20)),
                ('purpose', models.CharField(blank=True, help_text='查询用途（授权书）', max_length=255)),
                ('openid', models.CharField(blank=True, help_text='微信 openid（JSAPI 支付）', max_length=64)),
                ('amount_fen', models.IntegerField(default=0, help_text='客户支付金额（分）')),
                ('status', models.CharField(choices=[('unpaid', '待支付'), ('paid', '已支付'), ('querying', '查询中'), ('done', '已完成'), ('failed', '失败')], default='unpaid', max_length=16)),
                ('platform_query_id', models.CharField(blank=True, max_length=64)),
                ('report_json', models.JSONField(blank=True, default=dict, help_text='平台返回的报告快照')),
                ('wechat_prepay_id', models.CharField(blank=True, max_length=64)),
                ('err_msg', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_local_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
