# Generated by Django 5.2.17 on 2026-09-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localorder',
            name='admin_remark',
            field=models.TextField(blank=True, default='', help_text='后台备注'),
        ),
        migrations.AddField(
            model_name='localorder',
            name='commission_fen',
            field=models.IntegerField(default=0, help_text='本单应给分销商的佣金（分）'),
        ),
        migrations.AddField(
            model_name='localorder',
            name='dist_code',
            field=models.CharField(blank=True, default='', help_text='分销商邀请码', max_length=32),
        ),
        migrations.AddField(
            model_name='localorder',
            name='distributor_id',
            field=models.IntegerField(blank=True, help_text='关联分销商主键', null=True),
        ),
        migrations.AddField(
            model_name='localorder',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='退款时间', null=True),
        ),
    ]
